# Deploy various kaspr custom resources
# -------------------------------------

# A list of kaspr to deploy.
apps:

- # Scheduler app name
  name: my-scheduler
  
  # Number of kafka scheduler workers.
  # Kafka topic partitions are distributed across workers.
  # Increase the number of workers for higher throughput. 
  # (The number of workers should be no more than the number of topic partitions)
  replicas: 1
  
  # Kafka bootstrap server URL(s)
  bootstrapServers: localhost:9092

  # TLS configuration. Provide an empty entry `{}` to enable TLS.
  tls: {}

  # Authentication type. 
  authentication:
    # Supported types are `scram-sha-256`, `scram-sha-512`, and `plain
    type: plain
    username: kafka-user
    passwordSecret:
      secretName: kafka-credentials
      passwordKey: password

  # Application configuration
  # See XXX for information about all available configurations.
  config:
    topicPartitions: 3
    webPort: 6065
    webMetricsBasePath: /scheduler/metrics
    schedulerCheckpointSaveIntervalSeconds: 5
    schedulerJanitorCleanIntervalSeconds: 20
    schedulerJanitorHighwaterOffsetSeconds: 86400

  # Resource requests and limits
  resources: {}
    # requests:
    #   cpu: 0.1
    #   memory: 512Mi
    # limits:
    #   cpu: 1
    #   memory: 512Mi
    
  # Data storage configuration
  storage:
    # Storage type must be 'persistent-claim'"
    type: persistent-claim
    # The storage class to use for dynamic volume allocation.
    class: standard
    # Defines the size of the persistent volume claim (i.e 1Gi). 
    size: 268Mi
    # Specifies if the persistent volume claim has to be deleted 
    # when the app is un-deployed.
    deleteClaim: True

# TODO
agents: []
tables: []
tasks: []
webviews: []    