{{- if .Values.agents }}
{{- $root := . -}}
{{- range .Values.agents }}
---
apiVersion: kaspr.io/v1alpha1
kind: KasprAgent
metadata:
  name: {{ .name }}
spec: 
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
