{{- if .Values.operator -}}
{{- if .Values.operator.enable -}}
{{- if and .Values.operator.rbac.create .Values.operator.createGlobalResources -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaspr-operator-watched
  labels:
    component: role
    {{- include "kaspr.operator.labels" . | nindent 4 }}
rules:
# Resources in this role are being watched by the operator. When operator is deployed as cluster-wide, these permissions
# need to be granted to the operator on a cluster wide level as well, even if the operands will be deployed only in
# few of the namespaces in given cluster. This is required to set up the Kubernetes watches and informers.
# Note: The rights included in this role might change in the future

# Runtime observation of namespaces & CRDs (addition/deletion).
- apiGroups: 
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs: 
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  verbs:
  - watch
  - list

- apiGroups:
  - "kaspr.io"
  resources:
  # The Kasp operator operates on these custom resources
  - kasprapps
  - kaspragents
  - kasprwebviews
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection
- apiGroups:
  - "kaspr.io"
  resources:
  # The Cluster Operator needs to manage the status of the Strimzi custom resources
  - kasprapps/status
  - kaspragents/status
  - kasprwebviews/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
{{- end -}}
{{- end -}}